@echo off
cd %~dp0
echo Removing All 64-Bit exe files to prevent build failures.
del "Build\x64\*.exe"
"%SystemDrive%\Python352x64\Scripts\pyinstaller.exe" --console -F -i "VP.ico" -m "manifest.xml" --upx-dir "upx" --distpath "%Build\x64" "DecoraterBot.py"
"Build\x64\DecoraterBot.exe"
"Build\x64\DecoraterBot.x64.win32.cpython-352.exe"
del "Build\DecoraterBot\*.*"
"Build\x64\DecoraterBot.exe"
"Build\x64\DecoraterBot.x64.win32.cpython-351.exe"
del "Build\DecoraterBot\*.*"
"Build\x64\DecoraterBot.exe"
"Build\x64\DecoraterBot.x64.win32.cpython-350.exe"
del "Build\DecoraterBot\*.*"
"Build\x64\DecoraterBot.exe"
"Build\x64\DecoraterBot.x64.win32.cpython-345.exe"
del "Build\DecoraterBot\*.*"
"Build\x64\DecoraterBot.exe"
"Build\x64\DecoraterBot.x64.win32.cpython-344.exe"
del "Build\DecoraterBot\*.*"
"Build\x64\DecoraterBot.exe"
"Build\x64\DecoraterBot.x64.win32.cpython-343.exe"
del "Build\DecoraterBot\*.*"
"Build\x64\DecoraterBot.exe"
"Build\x64\DecoraterBot.x64.win32.cpython-342.exe"
del "Build\DecoraterBot\*.*"
pause